#!/bin/bash
# Manual deployment guide for NIFTY strategies

echo "=========================================="
echo "Manual Deployment Guide"
echo "=========================================="
echo ""
echo "The top-ranked strategies to deploy are:"
echo "1. NIFTY Greeks Enhanced"
echo "2. NIFTY Multi-Strike Momentum"
echo ""
echo "Files are located at:"
echo "  - strategies/scripts/nifty_greeks_enhanced_20260122.py"
echo "  - strategies/scripts/nifty_multistrike_momentum_20260122.py"
echo ""
echo "To deploy via web UI:"
echo "1. Open: http://127.0.0.1:5001/auth/login"
echo "2. Login to OpenAlgo"
echo "3. Go to: http://127.0.0.1:5001/python/"
echo "4. Click 'Add Strategy'"
echo "5. For each strategy:"
echo "   - Name: 'NIFTY Greeks Enhanced'"
echo "   - File: Select 'nifty_greeks_enhanced_20260122.py'"
echo "   - Click 'Upload Strategy'"
echo "   - Repeat for 'NIFTY Multi-Strike Momentum'"
echo "6. After upload, click 'Start' for each strategy"
echo ""
echo "=========================================="
