#!/bin/bash
# Deployment Script Generated by EOD Optimization

BASE_URL="http://127.0.0.1:5001"

echo "🚀 Executing Deployment Plan..."

echo "✅ Starting mcx_commodity_momentum..."
curl -X POST $BASE_URL/python/start/mcx_commodity_momentum
echo ""
echo "✨ Deployment Complete."
